version: 2.1

orbs:
  gusto: gusto/gusto@volatile
  orbs:
    executors:
      cli:
        docker:
          - image: circleci/circleci-cli

jobs:
  lint:
    executor: gusto/node
    steps:
      - gusto/yarn-install
      - run: yarn lint
  validate:
    executor: orbs/cli
    steps:
      - checkout
      - run: bash scripts/pack-orbs.sh
      - run: bash scripts/validate-orbs.sh
  publish:
    executor: orbs/cli
    steps:
      - checkout
      - run: bash scripts/pack-orbs.sh
      - run: bash scripts/publish-orbs.sh

workflows:
  version: 2
  build:
    jobs:
      - lint
      - validate
      - publish:
          filters:
            branches:
              only: master
          requires:
            - lint
            - validate
