version: 2.1

orbs:
  compare-url: iynere/compare-url@1.2.0
  orbs:
    executors:
      cli:
        docker:
          - image: circleci/circleci-cli
      node:
        docker:
          - image: circleci/node:10

    commands:
      install:
        steps:
          - checkout
          - restore_cache:
              name: Restore Yarn Package Cache
              keys:
                - yarn-packages-{{ checksum "yarn.lock" }}
          - run:
              name: Install dependencies
              command: yarn --frozen-lockfile && git diff --exit-code
          - save_cache:
              name: Save Yarn Package Cache
              key: yarn-packages-{{ checksum "yarn.lock" }}
              paths:
                - ~/.cache/yarn

    jobs:
      lint:
        executor: node
        steps:
          - install
          - run: yarn lint
      validate:
        executor: cli
        steps:
          - checkout
          - run: ./scripts/validate-orbs.sh
      publish:
        executor: cli
        steps:
          - checkout
          - compare-url/use:
              command: ./scripts/publish-orbs.sh
              step-name: Publish modified orbs

workflows:
  version: 2
  build:
    jobs:
      - orbs/lint:
          name: lint
      - orbs/validate:
          name: validate
